services:
  app:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    container_name: ${APP_CONTAINER_NAME:-eshop_app}
    volumes:
      - ${APP_CODE_PATH:-./api}:/var/www/html
      - ${PHP_CONFIG_PATH:-./docker/php/php.ini}:/usr/local/etc/php/conf.d/custom.ini:ro
    networks:
      - app_network

  nginx:
    image: nginx:alpine
    container_name: ${NGINX_CONTAINER_NAME:-eshop_nginx}
    ports:
      - "${NGINX_HOST_PORT:-8080}:${NGINX_CONTAINER_PORT:-80}"
    volumes:
      - ${APP_CODE_PATH:-./api}:/var/www/html
      - ${NGINX_CONFIG_PATH:-./docker/nginx/default.conf}:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - app
      - frontend
    networks:
      - app_network

  frontend:
    build:
      context: ./frontend
      dockerfile: ../docker/node/Dockerfile
    container_name: ${FRONTEND_CONTAINER_NAME:-eshop_frontend}
    volumes:
      - ${FRONTEND_CODE_PATH:-./frontend}:/app
      - /app/node_modules
    ports:
      - "${FRONTEND_HOST_PORT:-3000}:3000"
    environment:
      - NODE_ENV=${NODE_ENV:-development}
      - VITE_API_BASE_URL=http://nginx:${NGINX_CONTAINER_PORT:-80}/api
    networks:
      - app_network
    command: ["pnpm", "dev", "--host", "0.0.0.0"]

networks:
  app_network:
    name: ${NETWORK_NAME:-eshop_network}
    driver: bridge
