# see https://symfony.com/doc/current/reference/configuration/framework.html
framework:
    secret: '%env(APP_SECRET)%'
    annotations: false
    http_method_override: false
    handle_all_throwables: true

    # Session configuration
    session:
        handler_id: null
        cookie_secure: auto
        cookie_samesite: lax
        storage_factory_id: session.storage.factory.native
        name: '%env(SESSION_NAME)%'
        cookie_lifetime: '%env(int:SESSION_COOKIE_LIFETIME)%'
        gc_maxlifetime: '%env(int:SESSION_GC_MAXLIFETIME)%'

    #esi: true
    #fragments: true
    php_errors:
        log: true

when@test:
    framework:
        test: true
        session:
            storage_factory_id: session.storage.factory.mock_file
